# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: "validate pull request"

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: composer validate
      shell: bash
      run: |
        composer validate
    - name: composer update
      shell: bash
      run: |
        composer self-update
        composer update --prefer-source --no-interaction --no-progress --no-suggest --prefer-lowest
    - name: run tests
      shell: bash
      run : |
        vendor/bin/phpunit --exclude-group functional
